import type { Metadata } from "next";
import "./globals.css";
import SocialIcon from "@/components/organisms/SocialIcon";

export const metadata: Metadata = {
  title: "Creando un dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body>
        <SocialIcon />
        {children}
      </body>
    </html>
  );
}
